<?php

namespace App\Services;

use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Facades\Log;
use Symfony\Component\Process\Process;

class FrpService
{
    private string $host;
    private string $user;
    private string $configPath;
    private string $sshOptions;

    public function __construct()
    {
        $this->host       = config('frp.host');
        $this->user       = config('frp.user');
        $this->configPath = config('frp.config_path');
        $this->sshOptions = config('frp.ssh_options');
    }

    /* =========================================================
     | PUBLIC SYNC (SOURCE OF TRUTH)
     ========================================================= */

    public function sync(array $proxies): bool
    {
        return Cache::lock('frp-sync-global', 30)->block(10, function () use ($proxies) {

            $config = $this->buildConfig($proxies);

            $this->validateConfig($config);

            return $this->deploy($config);
        });
    }

    /* =========================================================
     | BUILD FULL CONFIG
     ========================================================= */

    private function buildConfig(array $proxies): string
    {
        $out = "# AUTO-GENERATED BY SAAS CORE\n";
        $out .= "# DO NOT EDIT MANUALLY\n\n";

        foreach ($proxies as $p) {

            $out .= "[[proxies]]\n";
            $out .= "name = \"{$p['name']}\"\n";
            $out .= "type = \"tcp\"\n";
            $out .= "localIP = \"127.0.0.1\"\n";
            $out .= "localPort = {$p['localPort']}\n";
            $out .= "remotePort = {$p['remotePort']}\n\n";
        }

        return $out;
    }

    /* =========================================================
     | DEPLOY ATOMIC (SAFE PRODUCTION METHOD)
     ========================================================= */

    private function deploy(string $config): bool
    {
        return Cache::lock('frp-deploy', 30)->block(10, function () use ($config) {

            $escaped = str_replace("'", "'\\''", $config);

            $commands = [

                // 1. backup actual config
                "sudo cp {$this->configPath} {$this->configPath}.bak",

                // 2. write new config atomically
                "echo '{$escaped}' | sudo tee {$this->configPath} > /dev/null",

                // 3. validate (if binary supports it)
                "frpc verify -c {$this->configPath} || exit 1",

                // 4. reload service
                "sudo systemctl reload frpc || sudo systemctl restart frpc",

                // 5. ensure service is alive
                "sudo systemctl is-active frpc",
            ];

            $process = $this->ssh($commands);
            $process->run();

            if (!$process->isSuccessful()) {

                $this->rollback();

                Log::error('FRP deploy failed', [
                    'error' => $process->getErrorOutput(),
                ]);

                return false;
            }

            Log::info('FRP deploy success');

            return true;
        });
    }

    /* =========================================================
     | ROLLBACK (CRITICAL SAFETY)
     ========================================================= */

    private function rollback(): void
    {
        $this->ssh([
            "sudo cp {$this->configPath}.bak {$this->configPath}",
            "sudo systemctl restart frpc",
        ])->run();
    }

    /* =========================================================
     | VALIDATION
     ========================================================= */

    private function validateConfig(string $config): void
    {
        if (!str_contains($config, '[[proxies]]')) {
            throw new \RuntimeException('FRP config invalid: no proxies defined');
        }
    }

    /* =========================================================
     | SSH WRAPPER
     ========================================================= */

    private function ssh(array $commands): Process
    {
        $cmd = implode(' && ', $commands);

        return Process::fromShellCommandline(
            "ssh {$this->sshOptions} {$this->user}@{$this->host} '{$cmd}'"
        );
    }
}
